# Generated by Django 5.0.1 on 2024-02-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_pizza', models.CharField()),
                ('price', models.CharField()),
                ('size', models.CharField()),
            ],
        ),
    ]
