# Generated by Django 5.0.1 on 2024-02-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="orders",
            fields=[
                ("user_id", models.TextField()),
                ("pizza_name", models.TextField()),
                ("product_price", models.TextField()),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("size", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="pizza",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("pizza_name", models.TextField()),
                ("size", models.TextField()),
                ("price", models.TextField()),
                ("ingredients", models.TextField()),
            ],
        ),
    ]
